//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangaugeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangaugeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HrApp.Resources.LangaugeResource", typeof(LangaugeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acces Card Type.
        /// </summary>
        public static string AccesCardType {
            get {
                return ResourceManager.GetString("AccesCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Card Request.
        /// </summary>
        public static string Access_Card_Request {
            get {
                return ResourceManager.GetString("Access Card Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address while on leave.
        /// </summary>
        public static string Addresswhileonleave {
            get {
                return ResourceManager.GetString("Addresswhileonleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attandees.
        /// </summary>
        public static string Attandees {
            get {
                return ResourceManager.GetString("Attandees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attatchements.
        /// </summary>
        public static string Attatchements {
            get {
                return ResourceManager.GetString("Attatchements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention Request.
        /// </summary>
        public static string AttentionRequest {
            get {
                return ResourceManager.GetString("AttentionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back From Vacation Request.
        /// </summary>
        public static string BackFromVacationRequest {
            get {
                return ResourceManager.GetString("BackFromVacationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Login Page  &gt;.
        /// </summary>
        public static string BackToLoginPage {
            get {
                return ResourceManager.GetString("BackToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE.
        /// </summary>
        public static string Ballence {
            get {
                return ResourceManager.GetString("Ballence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Card Request.
        /// </summary>
        public static string BusinessCardRequest {
            get {
                return ResourceManager.GetString("BusinessCardRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Travel Request.
        /// </summary>
        public static string BusinessTravelRequest {
            get {
                return ResourceManager.GetString("BusinessTravelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقويم.
        /// </summary>
        public static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Company.
        /// </summary>
        public static string CertifiedCompany {
            get {
                return ResourceManager.GetString("CertifiedCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password?.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIn.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        public static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Request.
        /// </summary>
        public static string CreateNewRequest {
            get {
                return ResourceManager.GetString("CreateNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Bank IBAN.
        /// </summary>
        public static string CurrentBankIBAN {
            get {
                return ResourceManager.GetString("CurrentBankIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Bank Name.
        /// </summary>
        public static string CurrentBankName {
            get {
                return ResourceManager.GetString("CurrentBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total current sallery.
        /// </summary>
        public static string CurrentSallery {
            get {
                return ResourceManager.GetString("CurrentSallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody Request.
        /// </summary>
        public static string CustodyRequest {
            get {
                return ResourceManager.GetString("CustodyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directed To.
        /// </summary>
        public static string DirectedTo {
            get {
                return ResourceManager.GetString("DirectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Type.
        /// </summary>
        public static string DurationType {
            get {
                return ResourceManager.GetString("DurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible For Ticket.
        /// </summary>
        public static string EligibleForTicket {
            get {
                return ResourceManager.GetString("EligibleForTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Request.
        /// </summary>
        public static string EmailRequest {
            get {
                return ResourceManager.GetString("EmailRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name:.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Transfer Request.
        /// </summary>
        public static string EmployeeTransferRequest {
            get {
                return ResourceManager.GetString("EmployeeTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Re-Entry VISA Request.
        /// </summary>
        public static string ExitRe_EntryVISARequest {
            get {
                return ResourceManager.GetString("ExitRe-EntryVISARequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string Expiration_Date {
            get {
                return ResourceManager.GetString("Expiration Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Amount.
        /// </summary>
        public static string FinancialAmount {
            get {
                return ResourceManager.GetString("FinancialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Request.
        /// </summary>
        public static string FinancialRequest {
            get {
                return ResourceManager.GetString("FinancialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have an account.
        /// </summary>
        public static string HaveanAccount {
            get {
                return ResourceManager.GetString("HaveanAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN No..
        /// </summary>
        public static string IBANNo {
            get {
                return ResourceManager.GetString("IBANNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No..
        /// </summary>
        public static string IDNo {
            get {
                return ResourceManager.GetString("IDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Type.
        /// </summary>
        public static string IncreaseType {
            get {
                return ResourceManager.GetString("IncreaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance For.
        /// </summary>
        public static string InsuranceFor {
            get {
                return ResourceManager.GetString("InsuranceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Electronic Letter?.
        /// </summary>
        public static string IsElectronicLetter {
            get {
                return ResourceManager.GetString("IsElectronicLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Re-Entry VISA ?.
        /// </summary>
        public static string IsExitRentry {
            get {
                return ResourceManager.GetString("IsExitRentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position AR.
        /// </summary>
        public static string JobPositionAR {
            get {
                return ResourceManager.GetString("JobPositionAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position EN.
        /// </summary>
        public static string JobPositionEN {
            get {
                return ResourceManager.GetString("JobPositionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Requests.
        /// </summary>
        public static string LeaveRequests {
            get {
                return ResourceManager.GetString("LeaveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string leaveType {
            get {
                return ResourceManager.GetString("leaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Advice Request.
        /// </summary>
        public static string LegalAdviceRequest {
            get {
                return ResourceManager.GetString("LegalAdviceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Type.
        /// </summary>
        public static string LegalType {
            get {
                return ResourceManager.GetString("LegalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Requests.
        /// </summary>
        public static string Letter_Requests {
            get {
                return ResourceManager.GetString("Letter Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Detail.
        /// </summary>
        public static string LetterDetail {
            get {
                return ResourceManager.GetString("LetterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type.
        /// </summary>
        public static string LetterType {
            get {
                return ResourceManager.GetString("LetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LoanAmount {
            get {
                return ResourceManager.GetString("LoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Request.
        /// </summary>
        public static string LoanRequest {
            get {
                return ResourceManager.GetString("LoanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login  to continue.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        public static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Insurance Request.
        /// </summary>
        public static string MedicalInsuranceRequest {
            get {
                return ResourceManager.GetString("MedicalInsuranceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Details.
        /// </summary>
        public static string MeetingDetails {
            get {
                return ResourceManager.GetString("MeetingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name AR.
        /// </summary>
        public static string NameAR {
            get {
                return ResourceManager.GetString("NameAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name EN.
        /// </summary>
        public static string NameEN {
            get {
                return ResourceManager.GetString("NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Passport AR.
        /// </summary>
        public static string NameinPassportAR {
            get {
                return ResourceManager.GetString("NameinPassportAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in Passport EN.
        /// </summary>
        public static string NameinPassportEN {
            get {
                return ResourceManager.GetString("NameinPassportEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bank IBAN.
        /// </summary>
        public static string NewBankIBAN {
            get {
                return ResourceManager.GetString("NewBankIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bank Name.
        /// </summary>
        public static string NewBankName {
            get {
                return ResourceManager.GetString("NewBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Department.
        /// </summary>
        public static string NewDepartment {
            get {
                return ResourceManager.GetString("NewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please check your internet connection.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Installments.
        /// </summary>
        public static string NoOfInstallments {
            get {
                return ResourceManager.GetString("NoOfInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Requests Found.
        /// </summary>
        public static string NoRequestsFound {
            get {
                return ResourceManager.GetString("NoRequestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Services.
        /// </summary>
        public static string OnlineServices {
            get {
                return ResourceManager.GetString("OnlineServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverTime Request.
        /// </summary>
        public static string OverTimeRequest {
            get {
                return ResourceManager.GetString("OverTimeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No.
        /// </summary>
        public static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string PendingRequests {
            get {
                return ResourceManager.GetString("PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Request.
        /// </summary>
        public static string Permission_Request {
            get {
                return ResourceManager.GetString("Permission Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property	Asset.
        /// </summary>
        public static string PropertyAsset {
            get {
                return ResourceManager.GetString("PropertyAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason.
        /// </summary>
        public static string RejectionReason {
            get {
                return ResourceManager.GetString("RejectionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Passport Request.
        /// </summary>
        public static string RenewalPassportRequest {
            get {
                return ResourceManager.GetString("RenewalPassportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Residence Request.
        /// </summary>
        public static string RenewalResidenceRequestt {
            get {
                return ResourceManager.GetString("RenewalResidenceRequestt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Mobile No.
        /// </summary>
        public static string ReplacementMobileNo {
            get {
                return ResourceManager.GetString("ReplacementMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replecement Employee:.
        /// </summary>
        public static string ReplecementEmployee {
            get {
                return ResourceManager.GetString("ReplecementEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested on.
        /// </summary>
        public static string Requestedon {
            get {
                return ResourceManager.GetString("Requestedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resignation Reason.
        /// </summary>
        public static string ResignationReason {
            get {
                return ResourceManager.GetString("ResignationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resignation Request.
        /// </summary>
        public static string ResignationRequest {
            get {
                return ResourceManager.GetString("ResignationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Advance Request.
        /// </summary>
        public static string SalaryAdvance {
            get {
                return ResourceManager.GetString("SalaryAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Increase Request.
        /// </summary>
        public static string SalaryIncreaseRequest {
            get {
                return ResourceManager.GetString("SalaryIncreaseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Transfer Request.
        /// </summary>
        public static string SalaryTransferRequest {
            get {
                return ResourceManager.GetString("SalaryTransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Travel Cover.
        /// </summary>
        public static string SelectTravelCover {
            get {
                return ResourceManager.GetString("SelectTravelCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor internet connection or server is not responding.
        /// </summary>
        public static string ServerErrorOrNoInternetConnection {
            get {
                return ResourceManager.GetString("ServerErrorOrNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID No.
        /// </summary>
        public static string StaffIDNo {
            get {
                return ResourceManager.GetString("StaffIDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination Reason.
        /// </summary>
        public static string TerminationReason {
            get {
                return ResourceManager.GetString("TerminationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination Request&quot;.
        /// </summary>
        public static string TerminationRequest {
            get {
                return ResourceManager.GetString("TerminationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password?.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Working Day.
        /// </summary>
        public static string TheLastWorkingDay {
            get {
                return ResourceManager.GetString("TheLastWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Cash Request.
        /// </summary>
        public static string TicketCashRequest {
            get {
                return ResourceManager.GetString("TicketCashRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Type.
        /// </summary>
        public static string TicketType {
            get {
                return ResourceManager.GetString("TicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        public static string TimeIn {
            get {
                return ResourceManager.GetString("TimeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todays List.
        /// </summary>
        public static string TodaysList {
            get {
                return ResourceManager.GetString("TodaysList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Sponsorship Request.
        /// </summary>
        public static string TransferSponsorshipRequest {
            get {
                return ResourceManager.GetString("TransferSponsorshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Cover.
        /// </summary>
        public static string TraveCover {
            get {
                return ResourceManager.GetString("TraveCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Type.
        /// </summary>
        public static string TravelType {
            get {
                return ResourceManager.GetString("TravelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use My Name.
        /// </summary>
        public static string UseMyName {
            get {
                return ResourceManager.GetString("UseMyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way To Travel.
        /// </summary>
        public static string WayToTravel {
            get {
                return ResourceManager.GetString("WayToTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Mobile.
        /// </summary>
        public static string WorkMobile {
            get {
                return ResourceManager.GetString("WorkMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have NO Tasks For These Day.
        /// </summary>
        public static string YouHaveNOTasksForTheseDay {
            get {
                return ResourceManager.GetString("YouHaveNOTasksForTheseDay", resourceCulture);
            }
        }
    }
}
